/// Flutter icons FGTIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FGTIcons
///      fonts:
///       - asset: fonts/FGTIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FGTIcons {
  FGTIcons._();

  static const _kFontFam = 'FGTIcons';

  static const IconData facebook_app_symbol = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData twitter__1_ = const IconData(0xe803, fontFamily: _kFontFam);
}
