/// Flutter icons IconsFGT
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsFGT
///      fonts:
///       - asset: fonts/IconsFGT.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
///
import 'package:flutter/widgets.dart';

class IconsFGT {
  IconsFGT._();

  static const _kFontFam = 'IconsFGT';

  static const IconData twitter_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData facebook_1 = const IconData(0xe804, fontFamily: _kFontFam);
}
