/// Flutter icons Qrscanner
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Qrscanner
///      fonts:
///       - asset: fonts/Qrscanner.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Qrscanner {
  Qrscanner._();

  static const _kFontFam = 'Qrscanner';

  static const IconData qrcode = const IconData(0xe800, fontFamily: _kFontFam);
}
